-- Vaultix - Script de limpeza do schema
-- Execute este script ANTES de subir a aplicacao caso ja existam tabelas
-- da atividade anterior no schema RM563618.
--
-- Como executar no SQL Developer (FIAP):
--   1. Conecte com RM563618 / 300606
--   2. Abra este arquivo
--   3. Selecione tudo (Ctrl+A) e execute como script (F5)

-- Drop triggers (ignora erro se nao existirem)
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDIT_NOVO_INCIDENTE';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ESCALONA_STATUS_CRITICO';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDIT_RESOLUCAO_INCIDENTE';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDIT_ASSINATURA_VENCIDA';     EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Drop tabelas (CASCADE CONSTRAINTS para FKs)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDITORIA_SEGURANCA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INCIDENTE         CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ASSINATURA        CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLIENTE           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PLANO_ASSINATURA  CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIO           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "flyway_schema_history" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

COMMIT;
