-- V1: Schema base do Vaultix - Seguro de Identidade Digital
-- Tema 4 ESG: Governanca e Compliance

CREATE TABLE PLANO_ASSINATURA (
    ID_PLANO      NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_PLANO    VARCHAR2(50)  NOT NULL,
    VALOR_MENSAL  NUMBER(10,2)  NOT NULL,
    DESCRICAO     VARCHAR2(300),
    NIVEL         VARCHAR2(20)  NOT NULL
                  CONSTRAINT CK_NIVEL CHECK (NIVEL IN ('BASICO','PREMIUM','ENTERPRISE'))
);

CREATE TABLE CLIENTE (
    ID_CLIENTE   NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME         VARCHAR2(100) NOT NULL,
    EMAIL        VARCHAR2(100) NOT NULL UNIQUE,
    CPF          CHAR(11)      NOT NULL UNIQUE
                 CONSTRAINT CK_CPF CHECK (REGEXP_LIKE(CPF, '^\d{11}$')),
    TELEFONE     VARCHAR2(20),
    DT_CADASTRO  DATE          DEFAULT SYSDATE NOT NULL
);

CREATE TABLE ASSINATURA (
    ID_ASSINATURA  NUMBER       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE     NUMBER       NOT NULL,
    ID_PLANO       NUMBER       NOT NULL,
    DT_INICIO      DATE         DEFAULT SYSDATE NOT NULL,
    DT_VENCIMENTO  DATE         NOT NULL,
    STATUS         VARCHAR2(20) DEFAULT 'ATIVA' NOT NULL
                   CONSTRAINT CK_STATUS_ASIN CHECK (STATUS IN ('ATIVA','VENCIDA','CANCELADA','SUSPENSA')),
    CONSTRAINT FK_ASIN_CLI   FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_ASIN_PLANO FOREIGN KEY (ID_PLANO)   REFERENCES PLANO_ASSINATURA(ID_PLANO)
);

CREATE TABLE INCIDENTE (
    ID_INCIDENTE   NUMBER       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE     NUMBER       NOT NULL,
    TIPO_INCIDENTE VARCHAR2(50) NOT NULL
                   CONSTRAINT CK_TIPO_INC CHECK (TIPO_INCIDENTE IN (
                       'HACKING_CONTA','PHISHING','ROUBO_DADOS',
                       'DEEPFAKE','SEQUESTRO_CONTA','VAZAMENTO_DADOS','OUTRO'
                   )),
    DESCRICAO      VARCHAR2(500),
    DT_OCORRENCIA  DATE         DEFAULT SYSDATE NOT NULL,
    SEVERIDADE     VARCHAR2(20) DEFAULT 'MEDIA' NOT NULL
                   CONSTRAINT CK_SEVER CHECK (SEVERIDADE IN ('BAIXA','MEDIA','ALTA','CRITICA')),
    STATUS         VARCHAR2(25) DEFAULT 'ABERTO' NOT NULL
                   CONSTRAINT CK_STATUS_INC CHECK (STATUS IN (
                       'ABERTO','EM_ATENDIMENTO','AGUARDANDO_CLIENTE','RESOLVIDO','ENCERRADO'
                   )),
    CONSTRAINT FK_INC_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE AUDITORIA_SEGURANCA (
    ID_AUDITORIA  NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE    NUMBER        NOT NULL,
    ID_INCIDENTE  NUMBER,
    TIPO_ACAO     VARCHAR2(100) NOT NULL,
    DESCRICAO     VARCHAR2(500),
    DT_REGISTRO   DATE          DEFAULT SYSDATE NOT NULL,
    RESULTADO     VARCHAR2(200) DEFAULT 'PENDENTE',
    CONSTRAINT FK_AUD_CLI FOREIGN KEY (ID_CLIENTE)   REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_AUD_INC FOREIGN KEY (ID_INCIDENTE) REFERENCES INCIDENTE(ID_INCIDENTE)
);
