-- V3: Dados de teste

INSERT INTO PLANO_ASSINATURA (NOME_PLANO, VALOR_MENSAL, DESCRICAO, NIVEL)
VALUES ('Basico', 19.90, 'Monitoramento de dados e notificacoes de atividades suspeitas.', 'BASICO');

INSERT INTO PLANO_ASSINATURA (NOME_PLANO, VALOR_MENSAL, DESCRICAO, NIVEL)
VALUES ('Premium', 49.90, 'Tudo do Basico + auditoria mensal, recuperacao de conta e SLA 24h.', 'PREMIUM');

INSERT INTO PLANO_ASSINATURA (NOME_PLANO, VALOR_MENSAL, DESCRICAO, NIVEL)
VALUES ('Enterprise', 99.90, 'Tudo do Premium + consultoria juridica LGPD e monitoramento Dark Web.', 'ENTERPRISE');

INSERT INTO PLANO_ASSINATURA (NOME_PLANO, VALOR_MENSAL, DESCRICAO, NIVEL)
VALUES ('Basico Anual', 15.90, 'Plano Basico com cobranca anual - economia de 20%.', 'BASICO');

INSERT INTO PLANO_ASSINATURA (NOME_PLANO, VALOR_MENSAL, DESCRICAO, NIVEL)
VALUES ('Premium Anual', 39.90, 'Plano Premium com cobranca anual - economia de 20%.', 'PREMIUM');

INSERT INTO PLANO_ASSINATURA (NOME_PLANO, VALOR_MENSAL, DESCRICAO, NIVEL)
VALUES ('Enterprise Anual', 79.90, 'Plano Enterprise com cobranca anual - economia de 20%.', 'ENTERPRISE');


INSERT INTO CLIENTE (NOME, EMAIL, CPF, TELEFONE)
VALUES ('Ana Lima', 'ana.lima@email.com', '11122233301', '(11) 91000-0001');

INSERT INTO CLIENTE (NOME, EMAIL, CPF, TELEFONE)
VALUES ('Bruno Mendes', 'b.mendes@email.com', '11122233302', '(11) 91000-0002');

INSERT INTO CLIENTE (NOME, EMAIL, CPF, TELEFONE)
VALUES ('Carla Souza', 'carla.souza@email.com', '11122233303', '(21) 91000-0003');

INSERT INTO CLIENTE (NOME, EMAIL, CPF, TELEFONE)
VALUES ('Diego Ferreira', 'diego.f@email.com', '11122233304', '(31) 91000-0004');

INSERT INTO CLIENTE (NOME, EMAIL, CPF, TELEFONE)
VALUES ('Eva Rodrigues', 'eva.r@email.com', '11122233305', '(11) 91000-0005');

INSERT INTO CLIENTE (NOME, EMAIL, CPF, TELEFONE)
VALUES ('Felipe Castro', 'f.castro@email.com', '11122233306', '(41) 91000-0006');

INSERT INTO CLIENTE (NOME, EMAIL, CPF, TELEFONE)
VALUES ('Giovanna Alves', 'gi.alves@email.com', '11122233307', '(51) 91000-0007');

INSERT INTO CLIENTE (NOME, EMAIL, CPF, TELEFONE)
VALUES ('Henrique Nunes', 'h.nunes@email.com', '11122233308', '(11) 91000-0008');


INSERT INTO ASSINATURA (ID_CLIENTE, ID_PLANO, DT_INICIO, DT_VENCIMENTO, STATUS)
VALUES (1, 1, DATE '2025-01-10', DATE '2026-01-10', 'ATIVA');

INSERT INTO ASSINATURA (ID_CLIENTE, ID_PLANO, DT_INICIO, DT_VENCIMENTO, STATUS)
VALUES (2, 2, DATE '2025-02-15', DATE '2026-02-15', 'ATIVA');

INSERT INTO ASSINATURA (ID_CLIENTE, ID_PLANO, DT_INICIO, DT_VENCIMENTO, STATUS)
VALUES (3, 3, DATE '2025-03-01', DATE '2026-03-01', 'ATIVA');

INSERT INTO ASSINATURA (ID_CLIENTE, ID_PLANO, DT_INICIO, DT_VENCIMENTO, STATUS)
VALUES (4, 1, DATE '2024-04-01', DATE '2025-04-01', 'VENCIDA');

INSERT INTO ASSINATURA (ID_CLIENTE, ID_PLANO, DT_INICIO, DT_VENCIMENTO, STATUS)
VALUES (5, 4, DATE '2025-05-10', DATE '2026-05-10', 'ATIVA');

INSERT INTO ASSINATURA (ID_CLIENTE, ID_PLANO, DT_INICIO, DT_VENCIMENTO, STATUS)
VALUES (6, 2, DATE '2025-06-01', DATE '2025-09-01', 'CANCELADA');

INSERT INTO ASSINATURA (ID_CLIENTE, ID_PLANO, DT_INICIO, DT_VENCIMENTO, STATUS)
VALUES (7, 5, DATE '2025-07-01', DATE '2026-07-01', 'ATIVA');

INSERT INTO ASSINATURA (ID_CLIENTE, ID_PLANO, DT_INICIO, DT_VENCIMENTO, STATUS)
VALUES (8, 3, DATE '2025-08-01', DATE '2026-08-01', 'ATIVA');


INSERT INTO INCIDENTE (ID_CLIENTE, TIPO_INCIDENTE, DESCRICAO, DT_OCORRENCIA, SEVERIDADE, STATUS)
VALUES (1, 'HACKING_CONTA', 'Conta do Instagram invadida. Senha alterada pelo atacante.', DATE '2025-03-05', 'ALTA', 'RESOLVIDO');

INSERT INTO INCIDENTE (ID_CLIENTE, TIPO_INCIDENTE, DESCRICAO, DT_OCORRENCIA, SEVERIDADE, STATUS)
VALUES (2, 'PHISHING', 'Usuario clicou em link falso e forneceu credenciais bancarias.', DATE '2025-04-12', 'MEDIA', 'RESOLVIDO');

INSERT INTO INCIDENTE (ID_CLIENTE, TIPO_INCIDENTE, DESCRICAO, DT_OCORRENCIA, SEVERIDADE, STATUS)
VALUES (3, 'ROUBO_DADOS', 'CPF e dados bancarios expostos em vazamento de marketplace.', DATE '2025-05-20', 'CRITICA', 'EM_ATENDIMENTO');

INSERT INTO INCIDENTE (ID_CLIENTE, TIPO_INCIDENTE, DESCRICAO, DT_OCORRENCIA, SEVERIDADE, STATUS)
VALUES (4, 'SEQUESTRO_CONTA', 'Conta profissional bloqueada. Atacante exige pagamento para devolucao.', DATE '2025-06-01', 'CRITICA', 'EM_ATENDIMENTO');

INSERT INTO INCIDENTE (ID_CLIENTE, TIPO_INCIDENTE, DESCRICAO, DT_OCORRENCIA, SEVERIDADE, STATUS)
VALUES (5, 'DEEPFAKE', 'Video falso com rosto do cliente usado em golpe financeiro.', DATE '2025-07-14', 'ALTA', 'ABERTO');

INSERT INTO INCIDENTE (ID_CLIENTE, TIPO_INCIDENTE, DESCRICAO, DT_OCORRENCIA, SEVERIDADE, STATUS)
VALUES (6, 'VAZAMENTO_DADOS', 'E-mail e telefone encontrados em base de dados da Dark Web.', DATE '2025-08-03', 'MEDIA', 'ABERTO');

INSERT INTO INCIDENTE (ID_CLIENTE, TIPO_INCIDENTE, DESCRICAO, DT_OCORRENCIA, SEVERIDADE, STATUS)
VALUES (7, 'HACKING_CONTA', 'TikTok invadido. Publicacoes maliciosas feitas pelo atacante.', DATE '2025-09-10', 'ALTA', 'ABERTO');

INSERT INTO INCIDENTE (ID_CLIENTE, TIPO_INCIDENTE, DESCRICAO, DT_OCORRENCIA, SEVERIDADE, STATUS)
VALUES (8, 'PHISHING', 'Mensagem falsa do Nubank solicitando recadastro de dados.', DATE '2025-10-01', 'BAIXA', 'ABERTO');

INSERT INTO INCIDENTE (ID_CLIENTE, TIPO_INCIDENTE, DESCRICAO, DT_OCORRENCIA, SEVERIDADE, STATUS)
VALUES (1, 'VAZAMENTO_DADOS', 'E-mail corporativo encontrado em forum hacker - segundo incidente.', DATE '2025-11-05', 'MEDIA', 'ABERTO');
